FROM node:12.14 as build

WORKDIR /app

COPY package.json .

RUN npm install
RUN npm install -g @angular/cli

COPY . .

CMD ng build --prod --base-href=/vt-map-editor/ --output-path=dist

#######

FROM nginx

COPY --from=build /app/dist /usr/share/nginx/html

COPY docker/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
