= Configuration file

The configuration file is a regular JSON file. To configure the application you must first create a new configuration file `config.json` in the folder `src/assets/config` with the required content. For that copy or rename `config_template.json` to `config.json`.

== Template
Here is a template for the configuration:

```
{
    "titles": {
        "map": "Basis<span class=\"accent\">visualisierung</span>"
    },
    "mapService": {
        "url": "/map-service"
    },
    "mapView": {
        "url": "/map-view"
    },
    "map": {
        "maxZoom": 18,
        "startCenter": [9.361699,52.104253],
        "startZoom": 13,
        "showZoomLevel": false,
        "showScaleBar": true
    },
    "mapFunctions": {
        "navigation": {
            "show": true,
            "enabled": true
        },
        "info": {
            "show": true,
            "enabled": true
        },
        "search": {
            "show": true,
            "enabled": true
        },
        "routing": {
            "show": true,
            "enabled": false,
            "configuration": {
                "color": "#FF0000"
            }
        }
    },
    "basemaps": [
        {
            "name": "My Map",
            "imgUrl": "assets/images/thumbnails/basemap_color.png",
            "styling": "assets/basemaps/style.json"
        }
    ],
    "menuItems": [
        {
            "label": "Map",
            "icon": "map",
            "link": "map",
            "externalLink": false
        },
        {
            "label": "Legals",
            "icon": "lock",
            "link": "https://domain/path/...",
            "externalLink": true
        }
    "guiLayers": {
        "sortByName": true
    }
}
```

== Reference
=== titles
`map`: string

Header Title of page _map_. It can contain HTML tags.

=== mapService
`url`: string

URL of the back end service _VT Map Service_. It can be a relative URL, if VT Map Editor and VT Map Service are running on the same domain.

=== mapView
`url`: string

URL of application _VT Map View_. It can be a relative URL, if VT Map Editor and VT Map View are running on the same domain.

=== map
`maxZoom`: integer

Maximum zoom level of the map (\<= 22).

`startCenter`: [integer, integer]

Initial center coordinates of the map [latitude, longitude].

`startZoom`: integer

Initial zoom level of the map (\<= 2vt-map-view
Display current zoom level on the bottom of the map.

`showScaleBar`: true | false

Display a scale bar on the bottom of the map.

=== mapFunctions
==== navigation
`show`: true | false

Show / hide the toggle for the navigation function in the functions user interface.

`enabled`: true | false

Enable or disable the toggle by default.

==== info
`show`: true | false

Show / hide the toggle for the info function in the functions user interface.

`enabled`: true | false

Enable or disable the toggle by default.

==== search
`show`: true | false

Show / hide the toggle for the search function in the functions user interface. Settings `searchApi` and `searchApiKey` must be defined.

`enabled`: true | false

Enable or disable the toggle by default.

==== routing
`show`: true | false

Show / hide the toggle for the routing function in the functions user interface. The routing function is only embedded in published maps.

`enabled`: true | false

Enable or disable the toggle by default.

===== configuration
`color`: string

Hex color code (e.g. #FF0000) of the route.

=== basemaps
List of available basemaps in the application. Each item has the following attributes:

`name`: string

Label of the basemap.

`imgUrl`: string

URL to a thumbnail of the basemap styling. It can be a URL or a relative file path.

`styling`: string

URL to the JSON styling file of the basemap. It can be an absolute URL, a relative URL (with leading slash) or a relative file path (without leading slash).

`randomColors`: true | false

If set to _true_ the current map styling will be rendered with random colors when the button for this basemap is clicked. +
This attribute is optional. The default value is _false_ when the attribute is not specified.

=== menuItems
This array defines the items of the sidebar menu. Each item has the following attributes:

`label`: string

Label of the menu item that is displayed in the user interface.

`icon`: string

Name of the Material Design icon that is displayed in the user interface. For available icons see https://material.io/resources/icons

`link`: string

Either an Angular routing path (externalLink = false) of any URL (externalLink = true)

`externalLink`: true | false

If set to _true_ the menu item is a link that opens in a new browser window.

=== guiLayers
`sortByName`: true | false

true: Sort groups and group layers by their names. +
false: Sort groups and group layers by their appearance in the JSON styling.



