= Docker setup

== Local environment with Docker Hub images
If you want to run a local version of VT Map Editor and all related services, you can use the following Docker Compose file. You only need to create the following two files in the same folder and start it via Docker Compose.

.nginx.conf
```
server {
    listen       80;
    server_name  localhost;

    location /map-service/ {
    	proxy_pass http://map-service:5000/;
    }

    location /map-editor/ {
    	proxy_pass http://map-editor/map-editor/;
    }

    location /map-view/ {
    	proxy_pass http://map-view/map-view/;
    }

    location /styles/ {
    	proxy_pass http://styles/styles/;
    }

    location /fonts/ {
    	proxy_pass http://styles/fonts/;
    }

    location /sprites/ {
    	proxy_pass http://styles/sprites/;
    }
}
```

.docker-compose.yml
```
version: '3'
services:
    map-service:
        image: basisvisualisierung/vt-map-service
        environment:
            - VTMS_SEARCH_API=bkg
            - VTMS_SEARCH_API_KEY=XXX
    map-editor:
        image: basisvisualisierung/vt-map-editor
    map-view:
        image: basisvisualisierung/vt-map-view
    styles:
        image: basisvisualisierung/vt-styles
    nginx:
        image: nginx
        depends_on:
            - map-editor
            - map-service
            - map-view
            - styles
        ports:
            - "80:80"
        volumes:
            - .:/etc/nginx/conf.d

```

Now you can view VT Map Editor in a browser: link:http://localhost/map-editor[http://localhost/map-editor]

=== Change URL paths for Docker images

If you need to change the default URL paths of the Docker Hub images for VT Map Editor and VT Map View, you can use the following Dockerfiles.

.Dockerfile VT Map Editor (change path /map-editor to /map-editor-test)
```
FROM basisvisualisierung/vt-map-editor:latest

# Change directory name
RUN mv /usr/share/nginx/html/map-editor /usr/share/nginx/html/map-editor-test

WORKDIR /usr/share/nginx/html/map-editor-test

# Replace directory name in fiels
RUN sed -i 's/map-editor/map-editor-test/g' ./index.html
RUN sed -i 's/map-editor/map-editor-test/g' /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
```

.Dockerfile VT Map View (change path /map-view to /map-view-test)
```
FROM basisvisualisierung/vt-map-view:1.1.0

# Change directory name
RUN mv /usr/share/nginx/html/map-view /usr/share/nginx/html/map-view-test

WORKDIR /usr/share/nginx/html/map-view-test

# Replace directory name in fiels
RUN sed -i 's/map-view/map-view-test/g' ./index.html
RUN sed -i 's/map-view/map-view-test/g' /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
```

== Development environment

The instructions in this section assume you have cloned or downloaded the three repositories link:https://github.com/basisvisualisierung/vt-map-editor[VT Map Editor], link:https://github.com/basisvisualisierung/vt-map-service[VT Map Service] and link:https://github.com/basisvisualisierung/vt-styles[VT Styles], put them in the following folder structure and set them up like described in the repositories documentations:

```
-- /project folder
   |
   |-- /nginx
       |
       |-- nginx.conf
   |
   |-- /vt-map-editor
   |
   |-- /vt-map-service
   |
   |-- /vt-styles
   |
   |-- docker-compose.yml
```

Besides the repositories from GitHub, the folder structure contains a folder _nginx_ with a configuration file _nginx.conf_. nginx is used as reverse proxy to receive all requests on port 80 to avoid cross origin requests.

The repository _vt-styles_ contains two empty folders _fonts_ and _sprites_. Glyph sets and sprites, which are used by the styles, must be placed in this folders. You can get more information about this in the link:https://github.com/basisvisualisierung/vt-styles[VT Styles repository].

.nginx.conf
```
server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /map-service/ {
    	proxy_pass http://map-service:5000/;
    }

    location /map-editor/ {
    	proxy_pass http://map-editor:4200/map-editor/;
    }

    location /sockjs-node/ {
    	proxy_pass http://map-editor:4200/sockjs-node/;
    }

    location /map-view/ {
    	proxy_pass http://map-view:4201/map-view/;
    }

    location /styles/ {
    	proxy_pass http://styles/styles/;
    }

    location /fonts/ {
    	proxy_pass http://styles/fonts/;
    }

    location /sprites/ {
    	proxy_pass http://styles/sprites/;
    }
}
```

The Compose file `docker-compose.yml` can be used to start a complete development environment for VT Map Editor, including link:https://github.com/basisvisualisierung/vt-map-service[VT Map Service] and link:https://github.com/Basisvisualisierung/vt-map-editor/tree/master/projects/vt-map-view[VT Map View].

.docker-compose.yml
```
version: '3'
services:
    map-service:
        build: ./vt-map-service
        image: vt-map-service:latest
        ports:
            - "5000:5000"
        volumes:
            - ./vt-map-service/data:/service/data
        environment:
            - VTMS_SEARCH_API=bkg
            - VTMS_SEARCH_API_KEY=XXX
    map-editor:
        build: ./vt-map-editor
        image: vt-map-editor:latest
        ports:
            - "4200:4200"
            - "9876:9876"
        depends_on:
            - map-service
        volumes:
            - ./vt-map-editor:/app
            - /app/node_modules
        command: ng serve --host 0.0.0.0 --disable-host-check --port 4200 --base-href /map-editor/
    map-view:
        build: ./vt-map-editor
        image: vt-map-editor:latest
        ports:
            - "4201:4201"
        depends_on:
            - map-service
        volumes:
            - ./vt-map-editor:/app
            - /app/node_modules
        command: ng serve --host 0.0.0.0 --disable-host-check --project vt-map-view --port 4201 --base-href /map-view/
    styles:
        build: ./vt-styles
        image: vt-styles:latest
        volumes:
            - ./vt-styles/styles:/usr/share/nginx/html/styles
            - ./vt-styles/fonts:/usr/share/nginx/html/fonts
            - ./vt-styles/sprites:/usr/share/nginx/html/sprites
    nginx:
        image: nginx
        depends_on:
            - map-editor
            - map-service
            - map-view
            - styles
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
```

Now you can view VT Map Editor in a browser: link:http://localhost/map-editor[http://localhost/map-editor]
