name: Publish Docker image NIGHTLY

on:
  push:
    branches: develop

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push VT Map Editor
        id: docker_build_editor
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: basisvisualisierung/vt-map-editor:nightly
          file: ./Dockerfile-vt-map-editor-prod
      -
        name: Build and push VT Map View
        id: docker_build_view
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: basisvisualisierung/vt-map-view:nightly
          file: ./Dockerfile-vt-map-view-prod

